package com.george.backgammon.rendering;

/**
 * Canonical invisible backgammon map for the premium board template.
 *
 * v1.6.5 keeps the measured-point mapping model: gameplay follows the
 * actual geometry of every visible triangle rather than an evenly spaced grid.  Each point stores its base-left,
 * base-right and apex coordinates measured from the production artwork.  Checker
 * centres are calculated halfway between the two sloping triangle edges at the
 * checker's own Y position.
 *
 * The v1.6.5 production art is also horizontally rebalanced around the centre bar,
 * and these coordinates are the matching post-rebalance measurements. This keeps the
 * outer wood rails visually even without decoupling checker geometry from the artwork. All board themes must continue to use this exact
 * master geometry.
 */
public final class BoardMap {
    private BoardMap() {}

    public static final int MASTER_WIDTH_PX = 2048;
    public static final int MASTER_HEIGHT_PX = 977;
    public static final float MASTER_ASPECT = (float) MASTER_WIDTH_PX / MASTER_HEIGHT_PX;

    // v1.23 geometry lock: the physical field/bar boundaries are the source of truth.
    // Point bases are generated by partitioning each playable half into six exact columns,
    // so the first/last triangle can never leak into a side tray or centre bar.
    public static final float FIELD_LEFT_PX = 232.09f;
    public static final float FIELD_RIGHT_PX = 1836.44f;
    public static final float FIELD_TOP_PX = 58f;
    public static final float FIELD_BOTTOM_PX = 920f;
    public static final float BAR_LEFT_PX = 979.50f;
    public static final float BAR_RIGHT_PX = 1068.50f;

    public static final float FIELD_LEFT = FIELD_LEFT_PX / MASTER_WIDTH_PX;
    public static final float FIELD_RIGHT = FIELD_RIGHT_PX / MASTER_WIDTH_PX;
    public static final float FIELD_TOP = FIELD_TOP_PX / MASTER_HEIGHT_PX;
    public static final float FIELD_BOTTOM = FIELD_BOTTOM_PX / MASTER_HEIGHT_PX;

    public static final float LEFT_TRAY_LEFT = 76.71f / MASTER_WIDTH_PX;
    public static final float LEFT_TRAY_RIGHT = 215.37f / MASTER_WIDTH_PX;
    public static final float RIGHT_TRAY_LEFT = 1845.59f / MASTER_WIDTH_PX;
    public static final float RIGHT_TRAY_RIGHT = 1974.77f / MASTER_WIDTH_PX;

    public static final float BAR_LEFT = BAR_LEFT_PX / MASTER_WIDTH_PX;
    public static final float BAR_RIGHT = BAR_RIGHT_PX / MASTER_WIDTH_PX;

    public static final float TRIANGLE_HEIGHT = 368f / MASTER_HEIGHT_PX;

    // The polished board uses a regular six-column grid on each side of the bar.
    // Top and bottom share the exact same X geometry; only apex Y changes.
    public static final float[] TOP_BASE_LEFT_PX = buildBaseLeftPx();
    public static final float[] TOP_BASE_RIGHT_PX = buildBaseRightPx();
    public static final float[] TOP_APEX_X_PX = buildApexXPx();
    public static final float[] TOP_APEX_Y_PX = fill(419.0f);

    public static final float[] BOTTOM_BASE_LEFT_PX = buildBaseLeftPx();
    public static final float[] BOTTOM_BASE_RIGHT_PX = buildBaseRightPx();
    public static final float[] BOTTOM_APEX_X_PX = buildApexXPx();
    public static final float[] BOTTOM_APEX_Y_PX = fill(544.0f);

    private static float[] buildBaseLeftPx() {
        float[] out = new float[12];
        float leftW = (BAR_LEFT_PX - FIELD_LEFT_PX) / 6f;
        float rightW = (FIELD_RIGHT_PX - BAR_RIGHT_PX) / 6f;
        for (int i = 0; i < 6; i++) out[i] = FIELD_LEFT_PX + leftW * i;
        for (int i = 0; i < 6; i++) out[6 + i] = BAR_RIGHT_PX + rightW * i;
        return out;
    }

    private static float[] buildBaseRightPx() {
        float[] out = new float[12];
        float leftW = (BAR_LEFT_PX - FIELD_LEFT_PX) / 6f;
        float rightW = (FIELD_RIGHT_PX - BAR_RIGHT_PX) / 6f;
        for (int i = 0; i < 6; i++) out[i] = FIELD_LEFT_PX + leftW * (i + 1);
        for (int i = 0; i < 6; i++) out[6 + i] = BAR_RIGHT_PX + rightW * (i + 1);
        return out;
    }

    private static float[] buildApexXPx() {
        float[] left = buildBaseLeftPx();
        float[] right = buildBaseRightPx();
        float[] out = new float[12];
        for (int i = 0; i < out.length; i++) out[i] = (left[i] + right[i]) * 0.5f;
        return out;
    }

    private static float[] fill(float value) {
        float[] out = new float[12];
        for (int i = 0; i < out.length; i++) out[i] = value;
        return out;
    }

    // Source-art standards. Runtime controls final displayed diameter independently.
    public static final int CHECKER_CANVAS_PX = 512;
    public static final int CHECKER_VISIBLE_DIAMETER_PX = 448;
}
